services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-test
    restart: on-failure
    volumes:
      - ./init/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=ab_platform_test
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ab_platform_test"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - ab_net_test

  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka-test
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CREATE_TOPICS=ab_deltas:1:1,ab_snapshots_meta:1:1,ab_assignment_events:1:1
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - ab_net_test

  central-api:
    build:
      context: .
      dockerfile: cmd/central-api/Dockerfile
    container_name: central-api-test
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:8080/health"]
      interval: 5s
      timeout: 2s
      retries: 10
    networks:
      - ab_net_test

  example-sort-app:
    build:
      context: .
      dockerfile: cmd/example-sort-app/Dockerfile
    container_name: example-sort-app-test
    depends_on:
      kafka:
        condition: service_started
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8081/sort"]
      interval: 5s
      timeout: 2s
      retries: 10
    networks:
      - ab_net_test

  test-runner:
    image: imega/jq
    container_name: test-runner
    depends_on:
      central-api:
        condition: service_healthy
      example-sort-app:
        condition: service_healthy
    networks:
      - ab_net_test
    volumes:
      - ./test.sh:/test.sh
    entrypoint: ["/bin/sh", "/test.sh"]

volumes:
  postgres_test_data:
  kafka_test_data:

networks:
  ab_net_test:
    driver: bridge